apiVersion: v1
kind: Secret
metadata:
  name: tomcatsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |-
    eyJhdXRocyI6eyJkb2NrZXItc2VydmVyIjoiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIiwiZG9ja2VyLXVzZXJuYW1lIjoiaGFyc2hhaGQxOCIsImRvY2tlci1wYXNzd29yZCI6ImRja3JfcGF0X1M0WmVHeXJyMEVhMjRmNU5uR2h0OFNtZDA0dyIsImRvY2tlci1lbWFpbCI6ImhhcnNoYWhkODM5QGdtYWlsLmNvbSJ9fQo=
