apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appLabel }}
  ports:
    - name: podport
      protocol: TCP
      port: 8085
      targetPort: 8080
